import type { StockState } from "./types";

export const STORE_KEY = "stockevent_pro_v1";

export function defaultState(): StockState {
  return {
    articles: [
      {
        id: "a1",
        nom: "Chaise Napoléon dorée",
        ref: "MOB-001",
        cat: "Mobilier",
        qtyTotal: 150,
        qtyAff: 30,
        valUnit: 12000,
        seuilMin: 10,
        emoji: "🪑",
        notes: "Fournisseur: Déco Plus CI",
      },
      {
        id: "a2",
        nom: "Micro sans fil Shure",
        ref: "AV-014",
        cat: "Audiovisuel",
        qtyTotal: 24,
        qtyAff: 16,
        valUnit: 85000,
        seuilMin: 4,
        emoji: "🎤",
        notes: "Modèle BLX288/PG58",
      },
      {
        id: "a3",
        nom: "Guirlande LED 30m",
        ref: "DEC-022",
        cat: "Décoration",
        qtyTotal: 40,
        qtyAff: 38,
        valUnit: 18500,
        seuilMin: 10,
        emoji: "🌟",
        notes: "Blanc chaud 3000K",
      },
      {
        id: "a4",
        nom: "Nappe ronde blanc 240cm",
        ref: "VAI-008",
        cat: "Vaisselle",
        qtyTotal: 60,
        qtyAff: 55,
        valUnit: 4500,
        seuilMin: 20,
        emoji: "🍽",
        notes: "Lavage à 60°C",
      },
      {
        id: "a5",
        nom: "Projecteur LED PAR",
        ref: "AV-031",
        cat: "Audiovisuel",
        qtyTotal: 20,
        qtyAff: 2,
        valUnit: 120000,
        seuilMin: 4,
        emoji: "💡",
        notes: "RGB 150W",
      },
      {
        id: "a6",
        nom: "Canapé 3 places blanc",
        ref: "MOB-017",
        cat: "Mobilier",
        qtyTotal: 8,
        qtyAff: 2,
        valUnit: 250000,
        seuilMin: 2,
        emoji: "🛋",
        notes: "En réparation: 1 unité",
      },
      {
        id: "a7",
        nom: "Rideau velours noir 3m",
        ref: "TEX-005",
        cat: "Textile",
        qtyTotal: 30,
        qtyAff: 8,
        valUnit: 35000,
        seuilMin: 6,
        emoji: "🎭",
        notes: "Laize 3m",
      },
      {
        id: "a8",
        nom: "Table ronde 180cm",
        ref: "MOB-003",
        cat: "Mobilier",
        qtyTotal: 45,
        qtyAff: 10,
        valUnit: 28000,
        seuilMin: 8,
        emoji: "🪵",
        notes: "Pliante aluminium",
      },
    ],
    evenements: [
      {
        id: "e1",
        nom: "Gala Entreprise NSIA",
        client: "NSIA Assurances",
        debut: "2025-06-14",
        fin: "2025-06-15",
        lieu: "Sofitel Abidjan",
        resp: "Kofi Mensah",
        statut: "Prêt",
        notes: "",
      },
      {
        id: "e2",
        nom: "Mariage Konan–Brou",
        client: "Famille Konan",
        debut: "2025-06-15",
        fin: "2025-06-15",
        lieu: "Villa Cocody",
        resp: "Sarah Lozano",
        statut: "En préparation",
        notes: "200 convives",
      },
      {
        id: "e3",
        nom: "Conférence SIE 2025",
        client: "SIE Côte d'Ivoire",
        debut: "2025-06-18",
        fin: "2025-06-19",
        lieu: "CCIAD Plateau",
        resp: "Aminata Diallo",
        statut: "Planifié",
        notes: "",
      },
      {
        id: "e4",
        nom: "Anniversaire Dupont",
        client: "Marc Dupont",
        debut: "2025-06-22",
        fin: "2025-06-22",
        lieu: "Plateau Résidentiel",
        resp: "Kofi Mensah",
        statut: "Planifié",
        notes: "Thème jardin",
      },
    ],
    mouvements: [
      {
        id: "m1",
        type: "Retour",
        articleId: "a1",
        qty: 50,
        evId: "e1",
        operateur: "Sarah L.",
        etat: "Bon état",
        note: "",
        date: "2025-06-12T09:14:00",
      },
      {
        id: "m2",
        type: "Sortie",
        articleId: "a2",
        qty: 8,
        evId: "e1",
        operateur: "Kofi M.",
        etat: "",
        note: "",
        date: "2025-06-12T08:30:00",
      },
      {
        id: "m3",
        type: "Retour",
        articleId: "a4",
        qty: 30,
        evId: "e2",
        operateur: "Kofi M.",
        etat: "Endommagé",
        note: "Taches de vin",
        date: "2025-06-11T17:20:00",
      },
      {
        id: "m4",
        type: "Sortie",
        articleId: "a3",
        qty: 15,
        evId: "e2",
        operateur: "Sarah L.",
        etat: "",
        note: "",
        date: "2025-06-11T10:00:00",
      },
      {
        id: "m5",
        type: "Réception",
        articleId: "a5",
        qty: 10,
        evId: "",
        operateur: "Aminata D.",
        etat: "",
        note: "Commande fournisseur #2304",
        date: "2025-06-10T15:45:00",
      },
      {
        id: "m6",
        type: "Perte",
        articleId: "a3",
        qty: 3,
        evId: "",
        operateur: "Kofi M.",
        etat: "Perdu",
        note: "Non retrouvé",
        date: "2025-06-10T09:00:00",
      },
    ],
    utilisateurs: [
      {
        id: "u1",
        prenom: "Aminata",
        nom: "Diallo",
        email: "aminata@eventagence.ci",
        role: "Administrateur",
        actif: true,
      },
      {
        id: "u2",
        prenom: "Kofi",
        nom: "Mensah",
        email: "kofi@eventagence.ci",
        role: "Gestionnaire",
        actif: true,
      },
      {
        id: "u3",
        prenom: "Sarah",
        nom: "Lozano",
        email: "sarah@eventagence.ci",
        role: "Magasinier",
        actif: true,
      },
      {
        id: "u4",
        prenom: "Marc",
        nom: "Touré",
        email: "marc@eventagence.ci",
        role: "Lecture seule",
        actif: false,
      },
    ],
    scanHistory: [],
    currentUser: "u1",
    calYear: new Date().getFullYear(),
    calMonth: new Date().getMonth(),
    mvtFilter: "",
    catFilter: "",
  };
}

